version: '3'
services:    
    cantinazo-app:
        image: jboss/wildfly-cantinazo
        container_name: cantinazo-app
        restart: unless-stopped
        ports:
            - "8181:8080"
            - "8444:8443"
            - "9991:9990"
        environment:
            - DRIVER_POSGRESQL_NAME=$DRIVER_POSGRESQL_NAME
            - DATASOURCE_NAME=$DATASOURCE_NAME
            - DATASOURCE_JNDI=$DATASOURCE_JNDI
            - DB_HOST=$DB_HOST
            - DB_PORT=$DB_PORT
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASS
            - DB_NAME=$DB_NAME